    <%@ Page Title="" Language="C#" MasterPageFile="~/admin.master" AutoEventWireup="true" CodeFile="manage_product.aspx.cs" Inherits="manage_product" %>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <section class="all_section">
     <h1 style="text-align:center;">Manage Product</h1>
    <center><asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="#CCCCCC" DataKeyNames="pro_id" DataSourceID="SqlDataSource1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        <Columns>
            <asp:BoundField DataField="pro_id" HeaderText="Product Id" ReadOnly="True" SortExpression="pro_id" InsertVisible="False" />
            <asp:BoundField DataField="pro_cat_id" HeaderText="Category Id" SortExpression="pro_cat_id" />
            <asp:BoundField DataField="pro_name" HeaderText="Product Name" SortExpression="pro_name" />
            <asp:BoundField DataField="pro_price" HeaderText="Price" SortExpression="pro_price" />
            <asp:BoundField DataField="pro_description" HeaderText="Description" SortExpression="pro_description" />
            <asp:BoundField DataField="pro_stock" HeaderText="Stock" SortExpression="pro_stock" />
        </Columns>
    </asp:GridView></center>
    <br />
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:autohubConnectionString2 %>" SelectCommand="SELECT [pro_id], [pro_cat_id], [pro_name], [pro_price], [pro_description], [pro_stock] FROM [tbl_product]" UpdateCommand="update tbl_product set pro_cat_id=@pro_cat_id,pro_name=@pro_name,pro_price=@pro_price,pro_description=@pro_description,pro_stock=@pro_stock where pro_id=@pro_id" DeleteCommand="delete from tbl_product where pro_id=@pro_id">
        <DeleteParameters>
            <asp:Parameter Name="pro_id" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="pro_cat_id" />
            <asp:Parameter Name="pro_name" />
            <asp:Parameter Name="pro_price" />
            <asp:Parameter Name="pro_description" />
            <asp:Parameter Name="pro_stock" />
            <asp:Parameter Name="pro_id" />
        </UpdateParameters>
     </asp:SqlDataSource>
    </section>
</asp:Content>

